CREATE TABLE Employee 
(
	EmployeeId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	BranchId BIGINT NOT NULL,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Email VARCHAR(255),
	PhoneNumber VARCHAR(20),
	BirthDate DATE NOT NULL,
	CreatedAt DATETIMEOFFSET(0) NOT NULL CONSTRAINT DF_Employee_CreatedAt DEFAULT SYSDATETIMEOFFSET(),

	CONSTRAINT PK_Employee PRIMARY KEY (EmployeeId),
	CONSTRAINT FK_Employee_Branch FOREIGN KEY (BranchId) REFERENCES Branch(BranchId)
);