INSERT INTO TransactionType (Name, Code, Description) 
VALUES
('Card payment', 'CARD_PAYMENT', 'Payment made by card'),
('Bank transfer', 'BANK_TRANSFER', 'Bank transfer'),
('ATM withdrawal', 'ATM_WITHDRAWAL', 'Cash withdrawal from ATM'),
('Cash deposit', 'CASH_DEPOSIT', 'Cash deposited into an account'),
('Salary', 'SALARY', 'Salary payment'),
('Direct debit', 'DIRECT_DEBIT', 'Direct debit payment'),
('Bank fee', 'BANK_FEE', 'Bank fee charged to the account'),
('Refund', 'REFUND', 'Refund of a previous payment'),
('Interest', 'INTEREST', 'Interest credited to the account'),
('Loan payment', 'LOAN_PAYMENT', 'Loan repayment'),
('Standing order', 'STANDING_ORDER', 'Payment generated by a standing order');